import Head from 'next/head'
import { motion } from 'framer-motion'
import Link from 'next/link'
import { CartSection } from '@/components/public/cart'

export default function PcRecommend() {
  return (
    <>
      <Head>
        <title>Spartan Hardware | Pc Recomendadas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        key="login"
        style={{ width: '100%' }}
      >
        <p style={{ margin: '164px 0 0 20px' }}>
          <Link passHref href="/">
            Home
          </Link>
          / <strong>Carrito de Compra</strong>
        </p>
        <CartSection />
      </motion.div>
    </>
  )
}
