import Head from 'next/head'

export default function PeripheralsPage() {
  return (
    <>
      <Head>
        <title>Spartan Hardware | Perifericos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Estoy en categoria Perifericos</div>
    </>
  )
}
