import Head from 'next/head'
import { motion } from 'framer-motion'
import { BuildPcComponent } from '@/components/public/buildPc'

export default function BuildPcPagFirstStep() {
  return (
    <>
      <Head>
        <title>Spartan Hardware | Arma tu PC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        key="build_pc"
        style={{ width: '100%', margin: '157px 0 0' }}
      >
        <p style={{ margin: '0 0 0 20px' }}>
          Home / <strong>Arma Tu Pc</strong>
        </p>
        <BuildPcComponent />
      </motion.div>
    </>
  )
}
