spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: spartanHardware
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS
server:
  error:
    whitelabel:
      enabled: false
name: prod-YAML
environment: production
enabled: true