import { Outstanding } from '@/components/public/home/Outstanding'
import { Content } from '@/components/public/Product/Content'
import Head from 'next/head'
import { useRouter } from 'next/router'
import BannerImg from '@/public/images/BannerPCSale.png'
import Image from 'next/image'
import Link from 'next/link'
import { motion } from 'framer-motion'

import { useQuery } from 'react-query'
import axios from 'axios'
import { ProductDetails } from '@/components/public/Product/ProductDetails'

export default function Product() {
  const router = useRouter()
  const { id } = router.query
  const URL_API = process.env.NEXT_PUBLIC_URL_API
  const { isLoading, error, data } = useQuery(['products', id], () =>
    axios
      .get(`${URL_API}/products/details/${id}`)
      .then((res) => res.data)
      .catch((e) => console.log(e.response)),
  )

  return (
    <>
      <Head>
        <title>Spartan Hardware | Inicio de sesion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        key="product"
        style={{ width: '100%', overflowX: 'hidden', maxWidth: '1920px' }}
      >
        <p style={{ margin: '147px 0 0 20px', textAlign: 'initial' }}>
          <Link passHref href="/">
            Home
          </Link>
          / PC´s Recomendadas / <strong>Detalle: {data?.name} </strong>
        </p>
        <ProductDetails data={data?.description} />
        <Content data={data} />
        <Outstanding />
      </motion.div>
    </>
  )
}
