import Head from 'next/head'
import Image from 'next/image'
import { motion } from 'framer-motion'
import { useRouter } from 'next/router'
import BannerImg from '@/public/images/BannerPCSale.png'
import { CatalogPcLow } from '@/components/public/PcRecommendSale/CatalogPcLow'
import Link from 'next/link'
import { useQuery } from 'react-query'
import axios from 'axios'

export default function CategoriesList() {
  const URL_API = process.env.NEXT_PUBLIC_URL_API
  const router = useRouter()
  const { id } = router.query

  const { isLoading, error, data } = useQuery(['byCategories', id], () =>
    axios
      .get(`${URL_API}/api/v1/products/filter?category=${id}&page=0`)
      .then((res) => res.data)
      .catch((e) => console.log(e.response)),
  )

  return (
    <>
      <Head>
        <title>Spartan Hardware | Pc Recomendadas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        key="login"
        style={{ width: '100%' }}
      >
        <Image
          src={BannerImg}
          alt="banner"
          style={{ marginTop: '137px', width: '100%' }}
          quality={100}
        />
        <p style={{ margin: '10px 0 0 20px' }}>
          <Link passHref href="/">
            Home
          </Link>
          / <strong>{router.query.id}</strong>
        </p>
        <CatalogPcLow items={data?.content} />
      </motion.div>
    </>
  )
}
